server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # 让 qiankun 在跨服务加载子应用资源时不至于被浏览器拦截
  add_header Access-Control-Allow-Origin "*" always;
  add_header Access-Control-Allow-Methods "GET,POST,OPTIONS" always;
  add_header Access-Control-Allow-Headers "*" always;

  location / {
    try_files $uri $uri/ /index.html;
  }
}

